endpoints:

  - type: http
    name: phani1
    url: https://httpbin.org/delay/2
  - type: http
    name: phani2
    url: https://httpbin.org/delay/2
  - type: http
    name: phani3
    url: https://httpbin.org/delay/2
  - type: http
    name: phani4
    url: https://httpbin.org/delay/2
  - type: http
    name: phani5
    url: https://httpbin.org/delay/2
  - type: http
    name: phani6
    url: https://httpbin.org/delay/2